No endpoints overview
advanced-rest-client/api-navigation pull request #26
Opened 2021-02-11 21:00 UTC by carowright

New property added: noOverview.
When set it will not render overview as a separated element for each endpoint. Overview will still be available when clicking on the endpoint path label.

2021-02-11 21:42 UTC, jarrodek requested changes
The overview is the way to enter the endpoint documentation page. Without it there's no other way to navigate there. I am opposing to this until you give me a valid use case.

2021-02-12 18:58 UTC, TwoPlusTwoOne commented
I believe the use case we need this for is for users who have a low endpoint-to-method ratio. We had complaints that there were too many "Overview" items when endpoints only had one method. The idea was to be able to remove the overview items and transfer the behavior of opening the endpoint documentation when clicking on the endpoint item.

I also think the behavior of expanding the endpoint item was going to be limited to just the arrow in the item. But I'm not sure if this was intended to be changed for all cases, or only when disabling the Overview items

2021-03-04 12:24 UTC, TwoPlusTwoOne approved these changes

2021-03-08 17:36 UTC, jarrodek approved these changes
LGTM

2021-03-08 17:44 UTC, merged